import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ThemeProvider } from "@/components/ui/theme/themeProvider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${inter.className} relative  `}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className=" container min-h-[calc(100vh_-_134px)] 2xl:mt-16 xl:mt-12">
              {children}
            </main>
            {/*<Footer />  */}
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
