import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./_components/Header";
const inter = Inter({ subsets: ["latin"] });
import { svSE } from "@clerk/localizations";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={svSE}>
      <html lang="en">
        <body className={inter.className}>
          <Header />

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
